# Generated by Django 4.1.1 on 2022-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0002_remove_book_rating_book_is_bestselling"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=35, null=True),
        ),
    ]
